defaults: &defaults
	host: localhost
	logger: true
#	  slaves:
#			- host: slave1.local
#				port: 27018
#	    - host: slave2.local
#				port: 27019

development:
	<<: *defaults
	database: print-health_api_development
	logger: true

test:
	<<: *defaults
	database: print-health_api_test

dev:
	<<: *defaults
	database: print-health_api

qa:
	<<: *defaults
	database: print-health_api


# Configurações de produção

#  host: <%= ENV['MONGOID_HOST'] %>
#	 port: <%= ENV['MONGOID_PORT'] %>
#	 username: <%= ENV['MONGOID_USERNAME'] %>
#	 password: <%= ENV['MONGOID_PASSWORD'] %>